# Generated by Django 4.2.5 on 2023-09-22 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('company_name', models.CharField(max_length=30)),
                ('vacancy', models.CharField(max_length=30, unique=True)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('salary', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('actuality', models.BooleanField(default=False)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
        ),
    ]
