# Generated by Django 4.2.5 on 2023-09-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_reqruiter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
