# Generated by Django 4.2.5 on 2023-09-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileReqruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('location', models.TextField()),
                ('company_phone', models.IntegerField()),
                ('amount_of_emplyees', models.IntegerField()),
                ('about_company', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('user_resume', models.FileField(upload_to='pdfs/')),
                ('about_user', models.TextField()),
            ],
        ),
    ]
